### ISSUE TITLE
Tool multiple upload broken after the latest version update

### ISSUE THREAD

**Issue by ElieMouawad** [jamesnovak/XrmDocumentTemplateManager#7]
<img width="863" alt="image" src="https://user-images.githubusercontent.com/12374614/204574625-286ec1d1-ecdf-4c95-b6c0-395cf74483af.png">

When trying to upload multiple files to replace the templates, the full menu is greyed out, no button is clickable and there's no way to get out of the menu unless I close the plugin and reload it.

I'm downgrading to the previous old version.

**Comment by MscrmTools** [comment]
Thank you for reporting, I will check this

**Comment by MscrmTools** [comment]
@ElieMouawad it seems a new version has been published on 12/9. Can you tell me if this version works better?

**Comment by ElieMouawad** [comment]
Yes I updated to that newer version and all is good. This one can be closed thanks!
